nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.6.0.cjs

packageExtensions:
  '@tanstack/eslint-plugin-query@*':
    peerDependencies:
      typescript: '*'
  '@tanstack/router-devtools@*':
    peerDependencies:
      csstype: '*'
  '@tiptap/starter-kit@*':
    peerDependencies:
      '@tiptap/pm': '*'