/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './../__root'
import { Route as IndexRouteImport } from './../index'
import { Route as LocaleLoginRouteRouteImport } from './../$locale/login/route'
import { Route as LocaleAboutRouteRouteImport } from './../$locale/about/route'
import { Route as LocaleAuthRouteRouteImport } from './../$locale/_auth/route'
import { Route as LocaleIndexRouteRouteImport } from './../$locale/index/route'
import { Route as LocaleAuthProfileRouteRouteImport } from './../$locale/_auth/profile/route'
import { Route as LocaleAuthDashboardRouteRouteImport } from './../$locale/_auth/dashboard/route'

const LocaleRouteImport = createFileRoute('/$locale')()

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleLoginRouteRoute = LocaleLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any).lazy(() =>
  import('./../$locale/login/route.lazy').then((d) => d.Route),
)
const LocaleAboutRouteRoute = LocaleAboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any).lazy(() =>
  import('./../$locale/about/route.lazy').then((d) => d.Route),
)
const LocaleAuthRouteRoute = LocaleAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleIndexRouteRoute = LocaleIndexRouteRouteImport.update({
  id: '/$locale/',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./../$locale/index/route.lazy').then((d) => d.Route),
)
const LocaleAuthProfileRouteRoute = LocaleAuthProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LocaleAuthRouteRoute,
} as any).lazy(() =>
  import('./../$locale/_auth/profile/route.lazy').then((d) => d.Route),
)
const LocaleAuthDashboardRouteRoute =
  LocaleAuthDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LocaleAuthRouteRoute,
  } as any).lazy(() =>
    import('./../$locale/_auth/dashboard/route.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleAuthRouteRouteWithChildren
  '/$locale/about': typeof LocaleAboutRouteRoute
  '/$locale/login': typeof LocaleLoginRouteRoute
  '/$locale/dashboard': typeof LocaleAuthDashboardRouteRoute
  '/$locale/profile': typeof LocaleAuthProfileRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleAuthRouteRouteWithChildren
  '/$locale/about': typeof LocaleAboutRouteRoute
  '/$locale/login': typeof LocaleLoginRouteRoute
  '/$locale/dashboard': typeof LocaleAuthDashboardRouteRoute
  '/$locale/profile': typeof LocaleAuthProfileRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale/': typeof LocaleIndexRouteRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_auth': typeof LocaleAuthRouteRouteWithChildren
  '/$locale/about': typeof LocaleAboutRouteRoute
  '/$locale/login': typeof LocaleLoginRouteRoute
  '/$locale/_auth/dashboard': typeof LocaleAuthDashboardRouteRoute
  '/$locale/_auth/profile': typeof LocaleAuthProfileRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/login'
    | '/$locale/dashboard'
    | '/$locale/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/login'
    | '/$locale/dashboard'
    | '/$locale/profile'
  id:
    | '__root__'
    | '/'
    | '/$locale/'
    | '/$locale'
    | '/$locale/_auth'
    | '/$locale/about'
    | '/$locale/login'
    | '/$locale/_auth/dashboard'
    | '/$locale/_auth/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleIndexRouteRoute: typeof LocaleIndexRouteRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_auth': {
      id: '/$locale/_auth'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthRouteRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_auth/profile': {
      id: '/$locale/_auth/profile'
      path: '/profile'
      fullPath: '/$locale/profile'
      preLoaderRoute: typeof LocaleAuthProfileRouteRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
    '/$locale/_auth/dashboard': {
      id: '/$locale/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleAuthDashboardRouteRouteImport
      parentRoute: typeof LocaleAuthRouteRoute
    }
  }
}

interface LocaleAuthRouteRouteChildren {
  LocaleAuthDashboardRouteRoute: typeof LocaleAuthDashboardRouteRoute
  LocaleAuthProfileRouteRoute: typeof LocaleAuthProfileRouteRoute
}

const LocaleAuthRouteRouteChildren: LocaleAuthRouteRouteChildren = {
  LocaleAuthDashboardRouteRoute: LocaleAuthDashboardRouteRoute,
  LocaleAuthProfileRouteRoute: LocaleAuthProfileRouteRoute,
}

const LocaleAuthRouteRouteWithChildren = LocaleAuthRouteRoute._addFileChildren(
  LocaleAuthRouteRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAuthRouteRoute: typeof LocaleAuthRouteRouteWithChildren
  LocaleAboutRouteRoute: typeof LocaleAboutRouteRoute
  LocaleLoginRouteRoute: typeof LocaleLoginRouteRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAuthRouteRoute: LocaleAuthRouteRouteWithChildren,
  LocaleAboutRouteRoute: LocaleAboutRouteRoute,
  LocaleLoginRouteRoute: LocaleLoginRouteRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleIndexRouteRoute: LocaleIndexRouteRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
